name: Nightly Mutation Testing

on:
  release:
    types: [created]
  schedule:
    - cron: '0 * * * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check Latest Commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=should_run::false" || echo "::set-output name=should_run::true"
    
  test:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    name: Mutation Testing
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of sonar reporting
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Get the repository name without owner
      run: echo REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/} >> $GITHUB_ENV
    - name: Execute Tests, Code Coverage, Mutation Testing and Publish Results to Sonar
      run: mvn test jacoco:report pitest:mutationCoverage sonar:sonar -Dsonar.host.url=http://leozvasconcellos-sonarqube.eastus.azurecontainer.io:9000/ -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=${{ github.repository_owner }}_${{ env.REPOSITORY_NAME }} -Dsonar.qualitygate.wait --batch-mode --file pom.xml
    - name: Get Sonar Mutation Coverage Score
      if: always()
      id: sonar_request
      uses: fjogeleit/http-request-action@v1
      with:
        url: "http://leozvasconcellos-sonarqube.eastus.azurecontainer.io:9000/api/measures/component?component=${{ github.repository_owner }}_${{ env.REPOSITORY_NAME }}&metricKeys=dc5_mutationAnalysis_mutations_coverage"
        method: "GET"
        username: ${{ secrets.SONAR_TOKEN }}
    - name: Create Mutation Coverage Badge
      if: always()
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: e5a4b68734f8ee29d54ecfe7b78b1cfb
        filename: ${{ env.REPOSITORY_NAME }}-mutation-coverage-badge.json
        label: mutation coverage
        message: ${{ fromJson(steps.sonar_request.outputs.response).component.measures[0].value }}%
        valColorRange: ${{ fromJson(steps.sonar_request.outputs.response).component.measures[0].value }}
        maxColorRange: 100
        minColorRange: 0
#    - name: SonarQube Quality Gate Check
#      id: sonarqube-quality-gate-check
#      uses: sonarsource/sonarqube-quality-gate-action@master
#      timeout-minutes: 5
#      env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         SONAR_HOST_URL: "http://leozvasconcellos-sonarqube.eastus.azurecontainer.io:9000/"
#      with:
#        scanMetadataReportFile: target/sonar/report-task.txt
#    - name: "Example show SonarQube Quality Gate Status value"
#      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
#    - name: Fail Job when Quality Gate fails
#      if: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }} == "FAILED"
#      uses: actions/github-script@v6
#      with:
#        script: |
#            core.setFailed('QUALITY GATE STATUS: FAILED')
